language: php
php:
    - 7.1
    - 7.2

install:
    # Install Nette Code Checker
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-progress

script:
    - php temp/code-checker --short-arrays --strict-types

before_script:
    - composer install --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache